### ISSUE TITLE
debuild -us -uc shows 3 failed tests

### ISSUE THREAD

**Issue by BryanQuigley** [tseliot/ubuntu-drivers-common#13]
Should they all be run in a chroot or something?
# 

FAIL: test_auto_install_system (ubuntu_drivers.ToolTest)
## ubuntu-drivers autoinstall for fake sysfs and system apt

Traceback (most recent call last):
  File "/mnt/store/git/ubuntu-drivers-common/tests/ubuntu_drivers.py", line 918, in test_auto_install_system
    self.assertEqual(err, '')
AssertionError: 'E: Could not open lock file /var/lib/dpkg[114 chars]t?\n' != ''
- E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
- E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
# 

FAIL: test_devices_system (ubuntu_drivers.ToolTest)
## ubuntu-drivers devices for fake sysfs and system apt

Traceback (most recent call last):
  File "/mnt/store/git/ubuntu-drivers-common/tests/ubuntu_drivers.py", line 867, in test_devices_system
    self.assertEqual(out, '')
AssertionError: '== /sys/devices/pci0000:00/0000:00:02.0/0[446 chars]\n\n' != ''
- == /sys/devices/pci0000:00/0000:00:02.0/0000:01:00.0 ==
- modalias : pci:v000010DEd00001380sv00003842sd00003751bc03sc00i00
- vendor   : NVIDIA Corporation
- model    : GM107 [GeForce GTX 750 Ti]
- driver   : nvidia-355 - third-party free recommended
- driver   : xserver-xorg-video-nouveau - distro free builtin
- driver   : nvidia-352-updates - distro non-free
- driver   : nvidia-352 - third-party free
- driver   : nvidia-340-updates - distro non-free
## \- driver   : nvidia-340 - distro non-free
# 

FAIL: test_list_system (ubuntu_drivers.ToolTest)
## ubuntu-drivers list for fake sysfs and system apt

Traceback (most recent call last):
  File "/mnt/store/git/ubuntu-drivers-common/tests/ubuntu_drivers.py", line 812, in test_list_system
    self.assertEqual(out, '\n')
AssertionError: 'nvidia-352-updates\nnvidia-340-updates\nnvidia-340\nnvidia-352\nnvidia-355\n' != '\n'
- 
- nvidia-352-updates
- nvidia-340-updates
- nvidia-340
- nvidia-352
- nvidia-355

---

Ran 91 tests in 136.232s

FAILED (failures=3)

**Comment by BryanQuigley** [comment]
workaround: DEB_BUILD_OPTIONS=nocheck debuild -us -uc

**Comment by martinpitt** [comment]
How exactly do you build this? Do you have all build dependencies installed?

**Comment by BryanQuigley** [comment]
Nothing special and yes I definitely have all build dependencies.
sudo apt-get build-dep ubuntu-drivers-common
sudo apt-get install devscripts
apt-get source ubuntu-drivers-common
cd ubuntu-drivers-common-0.4.11/
debuild -us -uc

The last two tests involve my specific Nvidia video card, which means I guess it is testing to make sure it reports nothing?

If I use a machine (in this case a cloud vm) without a proprietary graphics card it builds ok.

**Comment by tseliot** [comment]
Yes, that is an old issue where the real AMD or the NVIDIA GPU is detected by the tests which, therefore, fail.
