### ISSUE TITLE
Can fglrx support be removed?

### ISSUE THREAD

**Issue by BryanQuigley** [tseliot/ubuntu-drivers-common#26]
It isn't supported in 16.04 or 18.04 AFAICT.  Happy to do a pull request to remove them if so.

**Comment by tseliot** [comment]
I already have local changes to remove support for fglrx in gpu-manager, so, yes, that's the plan. If you want to help removing the driver from the rest of the package, you're more than welcome to send me a pull request.

**Comment by BryanQuigley** [comment]
Was removed, closing
