### ISSUE TITLE
on-demand graphics does not suspend card

### ISSUE THREAD

**Issue by crawfxrd** [tseliot/ubuntu-drivers-common#37]
Dynamic power management can be enabled in the `nvidia` driver with the option `NVreg_DynamicPowerManagement=0x02`. There are problems with PM that prevent NVIDIA Turing cards from suspending when not in use. The workaround for these problems is to remove the extra PCI functions for the card [\[1\]](https://download.nvidia.com/XFree86/Linux-x86_64/440.31/README/dynamicpowermanagement.html#KnownIssuesAndW6426e).

```
echo 1 > /sys/bus/pci/devices/<Domain>:<Bus>:<Device>.1/remove
echo 1 > /sys/bus/pci/devices/<Domain>:<Bus>:<Device>.2/remove
echo 1 > /sys/bus/pci/devices/<Domain>:<Bus>:<Device>.3/remove
```

Having `gpu-manager` perform this workaround until it's fixed would improve the experience with on-demand graphics, as users would then require less or no intervention to get the power savings.

**Comment by tseliot** [comment]
We currently don't enable dynamic power management because it still doesn't work with reverse prime, and also we don't have a good way to detect systems that are supported (not yet at least).

But yes, all this is in the plans.

**Comment by crawfxrd** [comment]
Going to close this, as I no longer see it on our kernel or the Ubuntu kernel in 20.04. Card goes into suspended state when not used.
