### ISSUE TITLE
Allow offloading with AMD APUs

### ISSUE THREAD

**Issue by crawfxrd** [tseliot/ubuntu-drivers-common#39]
We have users requesting the ability to render offloading on laptops with AMD APUs and NVIDIA GPUs (pop-os/system76-power#73), but `gpu-manager` does not support this configuration.

[LP#1878245](https://bugs.launchpad.net/ubuntu/+source/ubuntu-drivers-common/+bug/1878245)

**Comment by tseliot** [comment]
I'll have a look, and see what I can do.
