### ISSUE TITLE
Package nvidia-driver-440-server breaks nvidia-detector

### ISSUE THREAD

**Issue by blechta** [tseliot/ubuntu-drivers-common#46]
New packages
```python3
>>> import apt
>>> apt.Cache()['nvidia-driver-418-server'].get_changelog()
'nvidia-graphics-drivers-418-server (418.152.00-0ubuntu0.20.04.1) focal; urgency=medium\n\n  * Initial release (LP: #1881137).\n\n -- Alberto Milone <alberto.milone@canonical.com>  Wed, 17 Jun 2020 14:50:34 +0200\n'
>>> apt.Cache()['nvidia-driver-440-server'].get_changelog()
'nvidia-graphics-drivers-440-server (440.95.01-0ubuntu0.20.04.1) focal; urgency=medium\n\n  * Initial release (LP: #1881137).\n\n -- Alberto Milone <alberto.milone@canonical.com>  Wed, 17 Jun 2020 12:47:07 +0200\n'
```
break `nvidia-detector`:
```bash
$ nvidia-detector 
Traceback (most recent call last):
  File "/usr/bin/nvidia-detector", line 8, in <module>
    a = NvidiaDetection(printonly=True, verbose=False)
  File "/usr/lib/python3/dist-packages/NvidiaDetector/nvidiadetector.py", line 73, in __init__
    self.getData()
  File "/usr/lib/python3/dist-packages/NvidiaDetector/nvidiadetector.py", line 163, in getData
    driver_version = self.__get_value_from_name(stripped_package_name)
  File "/usr/lib/python3/dist-packages/NvidiaDetector/nvidiadetector.py", line 92, in __get_value_from_name
    v = int(name)
```

[On this line](../blob/9656229/NvidiaDetector/nvidiadetector.py#L162) it happens for these packages that  `stripped_package_name == 'server'` and this crashes the following line.

**Comment by tseliot** [comment]
Thanks for reporting the problem. I have filed the following bug report on launchpad:
https://bugs.launchpad.net/ubuntu/+source/ubuntu-drivers-common/+bug/1891183

**Comment by blechta** [comment]
Workaround: https://askubuntu.com/a/1265708/432023

**Comment by tseliot** [comment]
I have already fixed it in the master branch. I am going to upload the fix next week.

Here is the relevant commit:
https://github.com/tseliot/ubuntu-drivers-common/commit/ab1df35b85533198627e76b174f6cf84cb731205

**Comment by aerdnar** [comment]
There is a way to fix it on ubuntu bionic? Older version breaks dist-upgrade to focal as reported here https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/1891392 because Ubuntu Bionic has 0.5.2 version available https://packages.ubuntu.com/bionic/ubuntu-drivers-common

**Comment by tseliot** [comment]
I am going to backport the fix to Bionic and Focal.

**Comment by rajesh-s** [comment]
@aerdnar Did you happen to find any workaround for Bionic Beaver?

**Comment by rajesh-s** [comment]
> Workaround: https://askubuntu.com/a/1265708/432023

This works when invoking "nvidia-detector" from terminal. But on do-release-upgrade, main.log shows the same error. Do you happen to know what could be the issue?
