### ISSUE TITLE
dpkg: warning: version number does not start with digit

### ISSUE THREAD

**Issue by allanlaal** [tseliot/ubuntu-drivers-common#70]
Package: ubuntu-drivers-common           
Version: 1:0.9.6.1
	 

 root@L4:/lib/modprobe.d# ubuntu-drivers list
	  dpkg: warning: version 'unsigned-5.17.1-051701' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.0-051700' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.1-051701' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.1-051701' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.1-051701' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.2-051702' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.1-051701' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.16.18-051618' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.2-051702' has bad syntax: version number does not start with digit
	  nvidia-driver-390
	  dpkg: warning: version 'unsigned-5.17.1-051701' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.0-051700' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.1-051701' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.1-051701' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.1-051701' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.2-051702' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.1-051701' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.16.18-051618' has bad syntax: version number does not start with digit
	  dpkg: warning: version 'unsigned-5.17.2-051702' has bad syntax: version number does not start with digit
	  nvidia-driver-418-server

**Comment by os369510** [comment]
do you know which package (seems like kernel) contains those unexpected versions?

**Comment by EriksRemess** [comment]
Happens if you have unsigned kernel images installed. Fixed in #74
